# Setup
title:            My CS Ph.D.
tagline:          'Computer Science Ph.D. Information'
description:      'Whether, why, and how to get a Ph.D. in CS'
url:              https://mycsphd.github.io
github_username:  mycsphd
hydeout:
  repo:           https://github.com/mycsphd/mycsphd.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - github-pages

include:
  - _pages
  - _blog.html
  
paginate:         5
sidebar_home_link: true
remote_theme: fongandrew/hydeout